version: '3.8'

services:
  clickmetric:
    container_name: clickmetric
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MODULE=service
    ports:
      - "${SERVICE_PORT:-8080}:8080"
    environment:
      - KAFKA_HOST=kafka:${KAFKA_PORT:-9092}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      - kafka

  prometheus-exporter:
    container_name: prometheus-exporter
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MODULE=prometheus-exporter
    ports:
      - "${PROMETHEUS_PORT:-9100}:9100"
    environment:
      - PROMETHEUS_PORT=${PROMETHEUS_PORT:-9100}
      - KAFKA_HOST=kafka:${KAFKA_PORT:-9092}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      - kafka

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - prometheus-exporter

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
    volumes:
      - grafana-storage:/var/lib/grafana

  kafka:
    image: apache/kafka:latest
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
volumes:
  grafana-storage: